.PHONY: help install test test-fast lint format clean \
        all prepare-data compare-algorithms deep-clustering reports dashboard verify \
        ingest phase1 phase2 phase3

PY := python

# Default target: show what this project can do, in plain language.
help:
	@echo "Clustering analysis of credit-card transactions"
	@echo
	@echo "Setup"
	@echo "  make install             install the package and all extras"
	@echo "  make verify              quick health check (imports + fast tests)"
	@echo
	@echo "Run the analysis (each step is resumable; later steps reuse earlier output)"
	@echo "  make all                 run everything, start to finish"
	@echo "  make prepare-data        clean the data, build features, and test for group structure"
	@echo "  make compare-algorithms  compare the classical clustering algorithms, choose one"
	@echo "  make deep-clustering     train the neural models, then explain and audit the groups"
	@echo "  make reports             rebuild the PDF reports"
	@echo
	@echo "Explore the results"
	@echo "  make dashboard           open the interactive cluster explorer in a browser"
	@echo
	@echo "Development"
	@echo "  make test / test-fast / lint / format / clean"
	@echo
	@echo "The course's phase names also work as aliases: phase1, phase2, phase3."

install:
	$(PY) -m pip install -e ".[dev,pipeline,deep,app]"

# --- running the analysis --------------------------------------------------- #
# Every target drives DVC, so re-running is incremental: a step is skipped when
# its inputs have not changed, and its outputs are versioned rather than
# regenerated by hand.
all:
	dvc repro

prepare-data:
	dvc repro scale_reduce_tendency

compare-algorithms:
	dvc repro phase2

deep-clustering:
	dvc repro phase3

reports:
	dvc repro report

dashboard:
	streamlit run src/clustering_analysis/dashboard.py

# --- aliases matching the course's phase vocabulary ------------------------- #
ingest:
	dvc repro -f -s ingest

phase1: prepare-data

phase2: compare-algorithms

phase3: deep-clustering

# --- development ------------------------------------------------------------ #
test:
	pytest tests/ -v

test-fast:
	pytest tests/ -v -m "not slow"

lint:
	ruff check src tests

format:
	ruff check --fix src tests
	black src tests

verify:
	$(PY) -c "import clustering_analysis; print('package importable:', clustering_analysis.__version__)"
	pytest tests/ -m "not slow" -q

clean:
	find . -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true
	find . -name "*.pyc" -delete
	rm -rf .pytest_cache .ruff_cache .coverage htmlcov
